wandb_version: 1

learning_rate:
  desc: null
  value: 0.0001
architecture:
  desc: null
  value: ConvLSTMBig
dataset:
  desc: null
  value: Helheim, Aletsch, jakobshavn
epochs:
  desc: null
  value: 40
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.15.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1695674606.502209
    t:
      1:
      - 1
      - 54
      - 55
      2:
      - 1
      - 54
      - 55
      3:
      - 16
      - 23
      4: 3.10.13
      5: 0.15.11
      8:
      - 5
      13: linux-x86_64
